name: 'Slack Notify'
description: 'Notify GitHub commit action results via Slack'
inputs:
  slack-access-token:
    description: 'Slack Bot Token (starts with xoxb-) for posting messages'
    required: true
  github-access-token:
    description: 'GitHub Personal Access Token for GraphQL API access'
    required: true
  send-message-to-channel:
    description: 'Slack channel name (with #) or set to null to disable'
    required: false
  send-message-to-user:
    description: 'Set to true to send direct messages, false to disable'
    required: false
    default: 'false'
  commit-url:
    description: 'URL to the commit'
    required: true
  commit-author-username:
    description: 'GitHub username of commit author'
    required: true
  commit-author-email:
    description: 'Email of commit author'
    required: true
  commit-message:
    description: 'The commit message'
    required: true
  status-name:
    description: 'Name of the CI/CD job or check'
    required: true
  status-description:
    description: 'Description of the status'
    required: true
  status-conclusion:
    description: 'Result of the status check (success, failure, error)'
    required: true
  status-url:
    description: 'URL to the CI/CD job details'
    required: true
outputs:
  channel-slack-message-id:
    description: 'The Slack message timestamp (ID) of the message sent to channel'
  channel-slack-channel-id:
    description: 'The Slack channel ID where the message was sent'
  direct-slack-message-id:
    description: 'The Slack message timestamp (ID) of the direct message sent to user'
  direct-slack-user-id:
    description: 'The Slack user ID who received the direct message'
runs:
  using: 'node20'
  main: 'dist/index.js'
