name: 'Slack Notify'
description: 'Notify GitHub commit action results via Slack'
inputs:
  github_token:
    description: 'Access token for GitHub, used to get commit author SSO email'
    required: true
  slack_token:
    description: 'Access token for Slack, used to match commit emails to usernames'
    required: true
  slack_channel:
    description: 'Slack channel name where the action will post messages'
    required: false
  slack_user:
    description: 'Slack user email or identifier to send direct message to'
    required: false
  slack_message:
    description: 'Message to send to Slack'
    required: true
  github_org:
    description: 'GitHub organization name (optional, used for SAML identity resolution)'
    required: false
  github_username:
    description: 'GitHub username (optional, used for SAML identity resolution)'
    required: false
outputs:
  channel_slack_message_id:
    description: 'The Slack message timestamp (ID) of the message sent to channel'
  channel_slack_channel_id:
    description: 'The Slack channel ID where the message was sent'
  direct_slack_message_id:
    description: 'The Slack message timestamp (ID) of the direct message sent to user'
  direct_slack_user_id:
    description: 'The Slack user ID who received the direct message'
runs:
  using: 'node20'
  main: 'main.js'
